[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "polyjuice-ml-audio-ingest-common"
version = "0.0.1"
requires-python = ">=3.8"
readme = "README.md"
dependencies = []
